#!/bin/bash
#	
# -- LOGIN SHELL MENU --
#
# DESCRIPTION: 	A login shell for lab users to access racked devices
# DATE: 	Summer 2018
# AUTHOR: 	A HAL 9000 computer

## SOURCES ########################################################################
. /etc/config/customscripts/variables
. /etc/config/customscripts/power_menu

remove_route		# Remove the leftover IP route from loginshell_ipassign IMMEDIATELY

rackCheck		# Set CM IP addresses
variablesSSH		# Get variables to check for SSH IP address
traps			# Get traps
colours			# Get colours
graphics		# Get text menu graphics

## MAIN ###########################################################################
clear

# NOTE: The following two lines are used to display special warning message (e.g. upcoming maintenance) when users log in. Comment them out when not needed.
#echo -e "\n\e[41mPlease note that the power to the SIRC building will be shut off on Sunday March 24th for maintenance.\nAs such, the equipment will be unavailable starting at midnight on Sunday until late Sunday evening.\n\e[0m"
#read -p "Press [Enter] to continue..."

D=0
while [[ ${D} == 0 ]]; do
	clear
	echo -e "$loginshell_menu"
	#id -g -n DETERMINE ID STUFF PLZ
	
	read -p "  > " opt
	case $opt in
		1) ${PORT1};;
		2) ${PORT2};;
		3) ${PORT3};;
		4) ${PORT4};;
		5) ${PORT5};;
		6) ${PORT6};;
		7) ${PORT7};;
		8) ${PORT8};;
		p|P) clear; powerQuery; powerMenu;;		## POWERMENU
		x|X) D=1; break;;
		*) clear;;
	esac
done
