#!/bin/bash
#
# IP ASSIGNER
# This script is needed to get our RADIUS server to set group names depending
# on the IP address the CM is attempting to be logged in to through. Users are
# required to log in to their pods with a specific IP address. 
#
# Please configure this script as follows:
# 	- 172.16.0.x, where "x" corresponds to the pod number
#	- 172.16.0.251 is the RADIUS server
#	- 172.16.0.1xx is the CM's own NET1 IP address
# 
# NOTE: "exit 0" is *required* by pam_exec to know how to "leave" the script.

. /etc/config/customscripts/variables
rackCheck

# You can drop down to the shell within a VERY short window if this isn't here          
trap "" SIGINT SIGQUIT SIGTSTP

# Remove leftover IP route if it exists from a failed login attempt
if [[ $(ip route | grep "172.16.0.251 via 172.16.0.19") ]]; then
        echo "Found leftover IP route, removing"
        ip route del 172.16.0.251 via ${RACKIP}
fi

if [[ ${PAM_USER} != "root" ]] && [[ ${PAM_USER} != "scheduleadmin" ]]; then
	set_ip_route 1
	set_ip_route 2
fi

exit 0
